spring.application.name=gestion-alumnos

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.keepalive-time=0
spring.datasource.hikari.validation-timeout=3000

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

tuapp.jwtSecret=${TUAPP_JWTSECRET}
tuapp.jwtExpirationMs=${TUAPP_JWT_EXPIRATION_MS:604800000}